# Generated by Django 3.2.21 on 2023-09-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_guest_booking_guests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('day', 'time')},
        ),
    ]
