# Generated by Django 3.2.21 on 2023-10-04 01:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_alter_booking_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('day', 'time', 'customer')},
        ),
    ]
